### ISSUE TITLE
setup issue

### ISSUE THREAD

**Issue by SoTxJay** [evereux/flicket#12] opened 2018-11-06 19:22 UTC
Where should I start looking to solve this:

jj:~/python/flicket:$ python manage.py db init
Traceback (most recent call last):
  File "manage.py", line 7, in <module>
    from setup import RunSetUP
  File "/home/jj/python/flicket/setup.py", line 10, in <module>
    from application import db, app
  File "/home/jj/python/flicket/application/__init__.py", line 15, in <module>
    from application.flicket_api_v2.views import bp_api_v2
ImportError: No module named flicket_api_v2.views

**Comment by evereux** [comment] 2018-11-19 18:49
I can't reproduce this error with a fresh install from the latest Master or 0.1.7 branch.

This looks like it could be an error with an earlier cloned version?

**Comment by evereux** [comment] 2019-01-13 14:00
If you still have this problem with the latest master branch please post back. In the meantime I'm going to close this issue.

**Closed by evereux** 2019-01-13 14:00 UTC

**Comment by SoTxJay** [comment] 2019-04-30 01:20
I believe I fixed this by creating an empty __init__.py in flicket/application/flicket_api_v2
